// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gsu.petclinic.jsf;

import com.gsu.petclinic.jsf.ApplicationBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ApplicationBean_Roo_Configurable {
    
    declare @type: ApplicationBean: @Configurable;
    
}
