// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gsu.petclinic.jsf;

import com.gsu.petclinic.jsf.VetBean;
import java.io.Serializable;

privileged aspect VetBean_Roo_Serializable {
    
    declare parents: VetBean implements Serializable;
    
    private static final long VetBean.serialVersionUID = 1L;
    
}
