// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gsu.petclinic.jsf;

import com.gsu.petclinic.jsf.VisitBean;
import java.io.Serializable;

privileged aspect VisitBean_Roo_Serializable {
    
    declare parents: VisitBean implements Serializable;
    
    private static final long VisitBean.serialVersionUID = 1L;
    
}
