// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gsu.petclinic.domain;

import com.gsu.petclinic.domain.AbstractPerson;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AbstractPerson_Roo_Configurable {
    
    declare @type: AbstractPerson: @Configurable;
    
}
