// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gsu.petclinic.jsf.converter;

import com.gsu.petclinic.jsf.converter.OwnerConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect OwnerConverter_Roo_Configurable {
    
    declare @type: OwnerConverter: @Configurable;
    
}
