// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gsu.petclinic.jsf.converter;

import com.gsu.petclinic.jsf.converter.VisitConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VisitConverter_Roo_Configurable {
    
    declare @type: VisitConverter: @Configurable;
    
}
